[env]
TERM = "xterm-256color"

[window]
opacity = 0.85

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 20
y = 20

[window.class]
instance = "Terminal"
general = "Terminal"

[scrolling]
history = 3500

[font]
size = 12.0

[font.normal]
family = "Geist Mono"
style = "Regular"

[font.bold]
family = "Geist Mono"
style = "Bold"

[font.italic]
family = "Geist Mono"
style = "Italic"

[font.bold_italic]
family = "Geist Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[colors.primary]
background = "#0A0A0A"
foreground = "#EDEDED"

[colors.normal]
black = "#000000"
red = "#F75F8F"
green = "#62C073"
yellow = "#FF9907"
blue = "#52A8FF"
magenta = "#C472FB"
cyan = "#1DA9B0"
white = "#A1A1A1"

[colors.bright]
black = "#676767"
red = "#F75F8F"
green = "#62C073"
yellow = "#FF9907"
blue = "#52A8FF"
magenta = "#C472FB"
cyan = "#1DA9B0"
white = "#EDEDED"

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false

[terminal.shell]
program = "C:\\Program Files\\Git\\bin\\bash.exe"
args = ["--login", "-i"]
