# Window configuration
[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations = "none"
startup_mode = "Windowed"
opacity = 0.95
blur = true

# Scrolling settings
[scrolling]
history = 10000
multiplier = 3

# Font configuration
[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12

# Color scheme (Darker Tokyo Night theme)
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black = "#1b1d2b"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#c0caf5"

[colors.bright]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#c0caf5"

# Cursor settings
[cursor]
style = { shape = "underline", blinking = "On" }
blink_interval = 350
unfocused_hollow = false

# Mouse settings
[mouse]
hide_when_typing = true

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

# Shell settings
[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login", "-i"] }

# Selection settings
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true
